#pragma config(Motor,  port6,           wheel_LF,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           wheel_LB,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           wheel_RF,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           wheel_RB,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ** Motor and Sensor Setup **

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(1200)
#include "Vex_Competition_Includes.c"

#include "auton.c"
#include "parallax-library/main.c"

/*
  Pre-autonomous
*/

void pre_auton(){
  bStopTasksBetweenModes = false;
  initialize();
}

/*
 	Autonomous
*/

task autonomous(){
  stopTask(usercontrol);
	autonProcedure();
}

/*
	USER CONTROL
*/

task usercontrol(){
  stopTask(autonomous);

  int V, H;

  while(true){
		V = vexRT[Ch2];
		H = vexRT[Ch1];

		move(V, H, 0);

    userControlUpdate();
  }
}
