#pragma config(Sensor, in1,    POT_SENSOR,     sensorPotentiometer)
#pragma config(Sensor, dgtl2,  LIM_SWITCH,     sensorTouch)
#pragma config(Motor,  port1,           mobile_goal_lift_1, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           wheel_LF,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           wheel_LB,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           wheel_RF,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           wheel_RB,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mobile_goal_lift_2, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ** Motor and Sensor Setup **

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(1200)
#include "Vex_Competition_Includes.c"

#include "auton.c"
#include "parallax-library/main.c"

/*
  Pre-autonomous
*/

void pre_auton(){
  bStopTasksBetweenModes = false;
  initialize();
}

/*
 	Autonomous
*/

task autonomous(){
  stopTask(usercontrol);
	autonProcedure();
}

/*
	USER CONTROL
*/

pid mobileGoalPID;
sensor mobileGoalLift;
#define MOBILE_GOAL_KP -0.08
#define MOBILE_GOAL_KD -0.03
#define MOBILE_GOAL_DEFAULT_V 15
#define MOBILE_GOAL_MIN_V -127
#define MOBILE_GOAL_MAX_V 127

task usercontrol(){
  stopTask(autonomous);

  int V, H;

  mobileGoalPID.kp = MOBILE_GOAL_KP;
	mobileGoalPID.kd = MOBILE_GOAL_KD;
	initializeSensor(&mobileGoalLift, 1.0, in1, &mobileGoalPID);

  while(true){
		V = vexRT[Ch2];
		H = vexRT[Ch1];

		move(V, H*0.75, 0);

		if (vexRT[Btn7U] == 1) {

			while (sensorValue(LIM_SWITCH) != 1) {
				// move up
				motor[mobile_goal_lift_1] = -127;
				motor[mobile_goal_lift_2] = -127;
			}
			motor[mobile_goal_lift_1] = 0;
			motor[mobile_goal_lift_2] = 0;
		}

		if (vexRT[Btn7D] == 1) {

			while (sensorValue(POT_SENSOR) < 2700) {
				// move down
				motor[mobile_goal_lift_1] = 127;
				motor[mobile_goal_lift_2] = 127;
			}

			motor[mobile_goal_lift_1] = 0;
			motor[mobile_goal_lift_2] = 0;
		}

		if(vexRT[Btn7L] == 1){
			motor[mobile_goal_lift_1] = 127;
			motor[mobile_goal_lift_2] = 127;

			while (sensorValue(POT_SENSOR) < 2700) {
				// move down
				updateSensor(&mobileGoalLift);

				motor[mobile_goal_lift_1] = sensorHold(&mobileGoalLift, 2700, MOBILE_GOAL_DEFAULT_V, MOBILE_GOAL_MIN_V, MOBILE_GOAL_MAX_V);
				motor[mobile_goal_lift_2] = sensorHold(&mobileGoalLift, 2700, MOBILE_GOAL_DEFAULT_V, MOBILE_GOAL_MIN_V, MOBILE_GOAL_MAX_V);



				wait1Msec(10);
			}

			motor[mobile_goal_lift_1] = 0;
			motor[mobile_goal_lift_2] = 0;

		}


    userControlUpdate();
  }
}
